### ISSUE TITLE
re-enable macos arm builds

### ISSUE THREAD

**Issue by johnynek** [bazeltools/bzl-gen-build#15]
these were removed in this commit: 

https://github.com/bazeltools/bzl-gen-build/commit/9e2ed18763eb29442f45358828a997d8031fe259

From what Ian told me, we need cirrus to do this since github does not have macos arm workers. The rust bit isn't the problem since rust can cross-compile, but the native-image for the java + scala generators is a problem.

The last version with arm is 0.1-61 currently. It is considerably faster than running the x86 binary (Ian estimates about 10x and that is about what it looked like to me when I ran two runs, although I didn't time it). Bottom line is that it is very noticeable.

**Comment by ianoc** [comment]
That commit only refers to the rust code btw, not the graal builds. Those never were in a github action.

Looks to be all fixed now though in cirrus

**Comment by johnynek** [comment]
what changed? 

.66 has arm builds:

https://github.com/bazeltools/bzl-gen-build/releases/tag/v0.1-66

65 didn't

https://github.com/bazeltools/bzl-gen-build/releases/tag/v0.1-65

ahh, I see you pushed direct to main:

https://github.com/bazeltools/bzl-gen-build/commit/5ba1f186513035036276a4ac663431bf9489de39
