### ISSUE TITLE
Reduce dynamic linking to glibc

### ISSUE THREAD

**Issue by eed3si9n** [bazeltools/bzl-gen-build#42]
Now that GitHub stopped Bionic GitHub Actions, the binary are built using Focal (Ubuntu 20.04), which no longer works on Bionic (Ubuntu 18.04), which uses glibc 2.27.

Can this be resolved if we used MUSL?

```bash
cargo build --target x86_64-unknown-linux-musl
```

**Comment by ianoc** [comment]
Yep! using a musl builds at one point was more of a pain, but last i tried this for something it worked super well.
